### ISSUE TITLE
Condensed Sparsity on MLP-Mixer

### ISSUE THREAD

**Issue by abhishektyaagi** [calgaryml/condensed-sparsity#76]
Hi,

I am using the condensed sparsity repo on MLPMixer ([source code](https://github.com/lucidrains/mlp-mixer-pytorch)). My current implementation is available [here](https://github.com/abhishektyaagi/nmsparsity). 

In my [training script](https://github.com/abhishektyaagi/nmsparsity/blob/main/train_cifar10.py), I add the following lines to instantiate the `RigLConstFanScheduler`:

```python
# Recommended kwargs
scheduler_kwargs = dict(
    dense_allocation = (1 - sparsity),  # (1-sparsity) up to you to set 
    T_end = int(len(trainloader) * args.n_epochs * 0.75),   # optim step number at which to stop mask mutation, 75% is what we used. 
    # Will need to adjust for distributed training or grad accumulation, see https://github.com/calgaryml/condensed-sparsity/blob/main/src/rigl_torch/utils/rigl_utils.py#L239 for an example of how this can be calculated for more complex training runs. 
    dynamic_ablation = True,  # ablate low saliency neurons
    min_salient_weights_per_neuron = 0.3,  # 30% of sparse weights must be salient or else neuron is pruned
    no_ablation_module_names = list(net.named_modules())[-1][0],  # Important not to ablate your last layer as this would remove entire classes from consideration. 
)
scheduler = RigLConstFanScheduler(net, optimizer, **scheduler_kwargs)
```

I use the following command to train the network:

`reset && CUDA_VISIBLE_DEVICES=0 python train_cifar10.py --expName mlpMixerNM --opt adam --net mlpmixer --n_epochs 300 --lr 1e-3 --expNum 266 --sparsity 0.8`

But the training stops with the following error always after the 99th Epoch:

```
Epoch: 99
 [============================ 98/98 =============================>]  Step: 31ms | Tot: 4s643ms | Loss: 2.274 | Acc: 14.094% (7047/50000)                                                     
 [============================ 100/100 ===========================>]  Step: 5ms | Tot: 583ms | Loss: 2.112 | Acc: 21.880% (2188/10000)                                                        
Sun Aug  4 10:44:26 2024 Epoch 99, lr: 0.0010000, val loss: 211.23486, acc: 21.88000, sparsity: 0.8
Traceback (most recent call last):
  File "/localdisk/Abhishek/compareSparsity/nmsparsity/train_cifar10.py", line 377, in <module>
    scheduler()
  File "/localdisk/Abhishek/compareSparsity/nmsparsity/src/rigl_torch/rigl_scheduler.py", line 755, in __call__
    self._rigl_step()
  File "/localdisk/Abhishek/anaconda3/envs/snn/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/localdisk/Abhishek/compareSparsity/nmsparsity/src/rigl_torch/rigl_constant_fan.py", line 267, in _rigl_step
    score_grow = torch.abs(self.backward_hook_objects[idx].dense_grad)
TypeError: abs(): argument 'input' (position 1) must be Tensor, not NoneType
```
Do you have any comments on why that might be the case?

**Comment by mklasby** [comment]
Hey @abhishektyaagi, 
The backwards IndexMaskHook has not accumulated any gradients. This means that [this line](https://github.com/calgaryml/condensed-sparsity/blob/main/src/rigl_torch/rigl_scheduler.py#L58) returned False when given the current step number it should have returned True. 

Looking at your code, it appears you call the scheduler after calling test(): https://github.com/abhishektyaagi/nmsparsity/blob/main/train_cifar10.py#L377

This is causing the scheduler.step to be misaligned with your training loop, resulting in the gradients not being accumulated by the backwards hook. 

Please let me know if this solves your problem!

**Comment by abhishektyaagi** [comment]
Hi Mike,
Thank you for getting back to me. I have modified my [training script](https://github.com/abhishektyaagi/nmsparsity/blob/main/train_cifar10.py#L377) as per your suggestion.

I am attaching my weights and biases workspace [link](https://wandb.ai/atyagi/cifar10-challange/runs/xabb8naz?nw=nwuserabhishekdtu6). In this particular instant, sparsity is 0.5 and I am keeping lr=1e-4. A couple of questions:

1) I would like to add cosine annealing to the lr. Can i do that with the RigLConstFanScheduler()?
2) Any thoughts on why the accuracy drops after a few iterations?

**Comment by mklasby** [comment]
@abhishektyaagi 
Wandb link seems to be broken for me, is it a public link? 

Yes, you can use cosine annealing. We used the same in this repo, see: https://github.com/calgaryml/condensed-sparsity/blob/main/src/rigl_torch/optim/cosine_annealing_with_linear_warm_up.py. 

Are you using a pretrained MLP mixer or training from scratch? I'll have more to say about potential fixes for accuracy once I can view the wandb workspace.

**Comment by abhishektyaagi** [comment]
Sorry about this, Mike. I hope it is accessible now. If it is not, I am attaching a screenshot of the workspace.
![Screenshot 2024-08-19 at 10 12 41 PM](https://github.com/user-attachments/assets/2083160f-0c8f-4cf6-9547-0631f0b0fa8a)
![Screenshot 2024-08-19 at 10 13 06 PM](https://github.com/user-attachments/assets/3c458400-187f-47c3-a242-a711cd469741)

I will try to train with cosine annealing. And also, I am training this from scratch. I am curious to know how I can make sure that constant-fan-in sparsity gets a fair shot.

I will also try to use SRigL from Sparsimony

**Comment by mklasby** [comment]
@abhishektyaagi 

Interesting. I assume dense training or the method you are comparing with converges as expected (i.e, you don't see this stalled loss and accuracy)? 

It's possible that the `rigl.min_salient_weights_per_neuron` hyperparameter needs tuning of this model/dataset. Are you using the default value of 0.3 there? At 50% I don't expect much, if any, ablation to be triggered. But if for some reason the network width has been prematurely decreased it could be contributing to this problem.

**Comment by abhishektyaagi** [comment]
The dense model does converge as expected.

I use the default value of 0.3 for `rigl.min_salient_weights_per_neuron`. Maybe I can vary the value and see if it affects accuracy.

I kept 50% as I thought that would be a good starting point but I see your point. I will try the same experiment with sparsities 90% and up.
